source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'FastList' do
    pod "FLLogs", :git => 'https://github.com/Nickelfox/FLLogs.git'
    pod 'FormValidation', :git => 'https://github.com/Nickelfox/FormValidation.git', :branch => 'develop'
    pod 'MBProgressHUD', '~> 1.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'BSKeyboardControls', '~> 2.2'
end

target 'Model' do
    pod "FLLogs", :git => 'https://github.com/Nickelfox/FLLogs.git'
    pod 'FoxAPIKit', :git => 'https://github.com/Nickelfox/FoxAPIKit.git', :branch => 'bug-fixes'
end
